adds user authentication via JWT
rancher-government-carbide/carbide-images-api pull request #4
Opened 2023-12-29 01:24 UTC by clanktron

2023-12-29 01:30 UTC, clanktron commented
unique constraints on the username field need to be added, I'm considering adding this idempotently with a database procedure and a DROP IF EXISTS statement. That being said I'd like to chat with @amartin120 about how he wants the api interacting with the database schema before I do anything related to procedure modification, etc.

2023-12-29 17:51 UTC, mgogoi commented on pkg/api/middleware.go
> +	UserIdString := claims["userid"].(string)
The variable name should be camel-cased `userIdString`

2023-12-29 18:28 UTC, mgogoi requested changes

2023-12-29 18:28 UTC, mgogoi commented on pkg/api/user.go
> +	err := json.NewDecoder(r.Body).Decode(&newUser)
We can extract this code fragment into a separate function which is currently repeated in all the 3 functions  `userPost`, `userDelete`, and `loginPost` 

`err := json.NewDecoder(r.Body).Decode(&login)
if err != nil {
httpJSONError(w, err.Error(), http.StatusBadRequest)
log.Error(err)
return
}`

2023-12-29 18:28 UTC, mgogoi commented on pkg/api/user.go
> +	token, err := generateJWT(newUser)
`userPost` and `loginPost` share some code that generates a JWT token and sets a cookie. This should be refactored out to a separate function.

2023-12-29 18:28 UTC, mgogoi commented on pkg/database/schema.go
> +func ensureUsersTableConstraint(db *sql.DB) error {
Is this not used anymore? If not used maybe remove it?

2023-12-29 18:28 UTC, mgogoi commented on pkg/database/user.go
> +	rows, err := db.Query(`SELECT * FROM users`)
Not sure how many users we are dealing with here. Maybe add pagination support in the future.

2023-12-29 19:13 UTC, clanktron commented on pkg/api/router.go
> +	if !userIsAuthenticated(w, r) {
We can't necessarily add the check in front of all endpoints since some don't require authentication, namely the users and login endpoints. That being said the release endpoint did have a duplicate auth check that I just got rid of.

2023-12-29 19:15 UTC, clanktron commented on pkg/api/middleware.go
> +	UserIdString := claims["userid"].(string)
fixed

2023-12-29 19:26 UTC, clanktron commented on pkg/database/schema.go
> +func ensureUsersTableConstraint(db *sql.DB) error {
These were the schema related functions I wanted to consult @amartin120 about before I "enabled" them. The way they're written now isn't idempotent and will cause errors if the database already has them instantiated. A solution could be to recreate them on api startup but I don't think that'll scale very well with multiple replicas. I could certainly remove them for now and just stash them on my local machine until we figure out the best approach for such...if that's desired.

2023-12-29 19:49 UTC, clanktron commented on pkg/api/user.go
> +	token, err := generateJWT(newUser)
done

2023-12-29 20:02 UTC, mgogoi commented on pkg/api/router.go
> +	if !userIsAuthenticated(w, r) {
I'd say it would still make sense to extract that validation logic in a separate function as this would be repeated in `serveProduct`, `serveImage`, and `serveReleaseImageMapping` I think.

2023-12-29 20:04 UTC, mgogoi reviewed
This change looks good to me.

2023-12-29 20:16 UTC, mgogoi commented on pkg/api/router.go
> +	if !userIsAuthenticated(w, r) {
@clanktron - I just double checked `serveUser` which performs a DELETE and CREATE user I think. I'd think the user who is performing this should still be authenticated. So, should `serveLogin`.

2023-12-29 20:25 UTC, clanktron commented on pkg/api/router.go
> +	if !userIsAuthenticated(w, r) {
The DELETE user in serveUser requires the username and password to be sent as JSON in order for the user to be deleted. This is meant for existing users to be able to delete their accounts. The CREATE user is for new users to create accounts, requiring auth for this seems like a catch 22...we'd have to manually add each user in the database beforehand if we required auth for this. Same goes for serveLogin...how would users login if they're required to already be logged in.

2023-12-29 20:55 UTC, clanktron commented on pkg/api/user.go
> +	err := json.NewDecoder(r.Body).Decode(&newUser)
Something like this?
```
func decodeUser(w http.ResponseWriter, r *http.Request) (objects.User, error) {
	var user objects.User
	err := json.NewDecoder(r.Body).Decode(&user)
	if err != nil {
		return user, err
	}
	return user, nil
}
```
and then inside of userPost, userDelete, loginPost
```
newUser, err := decodeUser(w, r)
if err != nil {
	httpJSONError(w, err.Error(), http.StatusBadRequest)
	log.Error(err)
	return
}
```
I don't _necessarily_ think this would decrease lines of code or mental overhead since I would essentially just be replacing the json decoder with a custom "user only" decoder. Not sure if that's what you were envisioning. I suppose I could include the httpJSONError and log.Error in the decodeUser func as well, but I was trying to keep all http messages/logs in the route functions themselves...that way it's easier to tell at a glance exactly what a route is emitting, unless we think that benefit is moot.

2023-12-29 20:58 UTC, clanktron commented on pkg/database/user.go
> +	rows, err := db.Query(`SELECT * FROM users`)
Definitely a good point to consider, for now I think our userbase will be small enough that's its not a huge concern but I can certainly look into adding it.

2023-12-29 22:12 UTC, mgogoi commented on pkg/api/user.go
> +	err := json.NewDecoder(r.Body).Decode(&newUser)
The more we break into smaller functions, the cleaner it looks and is easier to read and maintain. To extend what you just suggested with `decodeUser()`, I'd change it to this

`
func decodeUser(w http.ResponseWriter, r *http.Request) (objects.User, error) {
	var user objects.User
	err := json.NewDecoder(r.Body).Decode(&user)
	if err != nil {
		httpJSONError(w, err.Error(), http.StatusBadRequest)
		log.Error(err)
		return user, err
	}
	return user, nil
}
`
And the clients would look like this:
`
newUser, err := decodeUser(w, r)
	if err != nil {
		return
	}
`

2023-12-29 23:31 UTC, mgogoi commented on pkg/api/router.go
> +	if !userIsAuthenticated(w, r) {
I think I am missing something here and don't understand why a DELETE needs special handling and is different.

2023-12-30 01:06 UTC, clanktron commented on pkg/api/router.go
> +	if !userIsAuthenticated(w, r) {
Deleting your account is something that I see requiring an additional level of confirmation (rather than just being logged in) and the most common way of providing this IMO is providing your username and password. We could certainly also require the user to be logged in as well, at that point we'd also need to check if the userid in the JWT is the corresponding userid to username and password provided in the json. I felt that providing username and password would be sufficient confirmation regardless of whether they're logged in currently or not.

2024-02-11 00:57 UTC, merged